services:
  db:
    image: postgres:16-alpine
    container_name: privaci_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: privaci
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/SCRIPT.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d privaci"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: privaci_backend
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/PrivaCI
      dockerfile: Dockerfile
    container_name: privaci_frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend/PrivaCI:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
